version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - kart-store-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/ksdb?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    networks:
      - kart-store-net
    environment:
      MYSQL_DATABASE: ksdb
      MYSQL_USER: ks_one
      MYSQL_PASSWORD: ks_pw
      MYSQL_ROOT_PASSWORD: ks_Rpw
networks:
  kart-store-net: