CREATE TABLE SALE (
 ID INT NOT NULL AUTO_INCREMENT,
 NUM_CONTROL VARCHAR(200) NOT NULL,
 CREATED DATETIME NOT NULL,
 PRODUCT_NAME VARCHAR(50) NOT NULL,
 PRODUCT_VALUE DECIMAL(5,2) NOT NULL,
 AMOUNT INT NOT NULL,
 ORDER_TOTAL DECIMAL(5,2) NOT NULL,
 CLIENT_ID INT NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
)  ENGINE=INNODB;